In [8]:
import numpy as np
import itertools

def get_H(m):
    cols = []
    for i in range(1, 2**m):
        b = format(i, f'0{m}b')
        cols.append([int(x) for x in b])
    return np.array(cols).T

def get_cw(G):
    k = G.shape[0]
    msgs = np.array(list(itertools.product([0, 1], repeat=k)))
    return np.dot(msgs, G) % 2

m = 3
n = 2**m - 1
exp_w = 2**(m - 1)

print(f"Проверка для m={m}")
print(f"Ожидается: n={n}, k={m}, вес={exp_w}\n")

H = get_H(m)
print("Матрица H:")
print(H, "\n")

cw = get_cw(H)

# Считаем веса ненулевых слов
nz_cw = cw[np.any(cw != 0, axis=1)]
w = np.sum(nz_cw, axis=1)
u_w = np.unique(w)

print("Уникальные веса ненулевых слов:", u_w)

dists = set()
for c1, c2 in itertools.combinations(cw, 2):
    d = np.sum(c1 != c2)
    dists.add(d)

print("Все попарные расстояния:", dists)

is_simplex_weights = (len(u_w) == 1 and u_w[0] == exp_w)
is_simplex_dists = (len(dists) == 1 and exp_w in dists)

print("\n--- Итог ---")
if is_simplex_weights and is_simplex_dists:
    print("Код дуальный Хэммингу — это симплекс")
else:
    print("Проверка провалилась, это не симплекс")

Проверка для m=3
Ожидается: n=7, k=3, вес=4

Матрица H:
[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]] 

Уникальные веса ненулевых слов: [4]
Все попарные расстояния: {4}

--- Итог ---
Код дуальный Хэммингу — это симплекс
